version: '3.8' # Vers√£o recomendada do Docker Compose

services:
  db:
    image: mysql:latest 
    container_name: mysql_database
    restart: always
    
    environment:
      MYSQL_ROOT_PASSWORD: ana 
      MYSQL_DATABASE: ninivi
      MYSQL_USER: ana
      MYSQL_PASSWORD: ana 
    
    ports:
      - "3377:3306" 
      
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
    driver: local